# Generated by Django 4.2.4 on 2023-08-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("soap", "Soaps"),
                    ("beardoils", "Beard Oils"),
                    ("sugarscrubs", "Sugar Scrubs"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Account",
        ),
    ]
