# Generated by Django 4.2.4 on 2023-08-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_product_category_delete_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("soap", "Bar Soaps"),
                    ("bathbombs", "Bath Bombs"),
                    ("beardbalms", "Beard Balms"),
                    ("beardoils", "Beard Oils"),
                    ("bodybutters", "Body Butters"),
                    ("sugarscrubs", "Sugar Scrubs"),
                    ("waxmelts", "Wax Melts"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/placeholder.png", null=True, upload_to=""
            ),
        ),
    ]
